### ISSUE TITLE
Updating README.md

### ISSUE THREAD

**Issue by aditya-garg-09-01-2002** [aditya-garg-09-01-2002/commencer#3]
**Describe the documentation updates required**
- Update the README.md file

**Reason for the update**
- Currently README file is not friendly.
- No clear segregation of documentation for developers using npm package, repository as a template, or doing further contributions.
- Enhancing designing of documentations.

**Expected outcome**
- Updating README to a user friendly and readable file
- It should be easily understandable for different class of developers a like.

**Additional context**
- Please use comments or create a new discussion (preferable) to understand exact process to use the repo as intended to create a suitable README file.

**Comment by Akshay-66** [comment]
Can i work on this, I'm here to contribute as a part of hacktoberfest, and it would be my first ever. 
Can you assign and guide the further steps if you can?

**Comment by aditya-garg-09-01-2002** [comment]
Hi!!! @Akshay-66 

- You can go ahead and add the following data to readme file
- different API endpoints created and been used.
  - you can refer to /src/routes/user/index.ts file for getting to know different endpoints 
  - all end points in this file will be regarded as /auth/<route-you-see-at start>
  - all routes are like router.<method>(<route>,middleware(if any), controller)
  - you can list out these endpoints, and their input requirements are and what they do.
  - you can go ahead with listing only one, you can select any I will help you understand it.
  - you can focus on designing the actual Readme file, its .md file, pretty similar to .HTML, you can look forward to chatgpt for it as well.
- for knowing, how to start you can check out the discussion, it has the necessary steps for you start contributing and if you still need some help, I am here to help.
- Happy Contributing!!!

**Comment by Akshay-66** [comment]
Ok Thank you @aditya-garg-09-01-2002 
I'll list the process below please let me know if i'm wrong

fock repo -> create CONTRIBUTING.md file add readme.md content and push
or do i need to add readme.md directly into root.

**Comment by aditya-garg-09-01-2002** [comment]
- first of all, fork the repo
- then clone your repo to local system or just update the existing README.md file in root folder
- commit changes to the fork
- create a pull request in this repo

**Comment by Akshay-66** [comment]
Thank you @aditya-garg-09-01-2002 will do my best

**Comment by Akshay-66** [comment]
Done with PR for Readme.md file @aditya-garg-09-01-2002 
take a look and reach me back.

**Comment by aditya-garg-09-01-2002** [comment]
Thanks for the contribution !!!

Closed with PR #28
