### ISSUE TITLE
[Documentation Requirement] Listing all API endpoints for auth feature

### ISSUE THREAD

**Issue by aditya-garg-09-01-2002** [aditya-garg-09-01-2002/commencer#43]
**Describe the documentation updates required**
- Listing all APIs created under auth feature
- Defining methods used
- Defining inputs required
- Defining expected outputs and errors generated

**Reason for the update**
- To help external developers understand how to use auth feature

**Expected outcome**
- Production of understandable documentation under /docs folder 

**Additional context**
- [ ] /register-user
- [ ] /login
- [ ] /logout
- [ ] /forgot-password
- [ ] /change-password
- [ ] /resend-otp
- [ ] /set-password
- [ ] /reset-password
- [ ] /remove-user

**Comment by SKRILLAP** [comment]
I want to work on this , kindly allot me this issue.

**Comment by aditya-garg-09-01-2002** [comment]
Assigning this issue to @SKRILLAP , do create a docs folder, which will hold a auth.md file representing all the documentation of APIs for auth feature.
