### ISSUE TITLE
[Bug]: Fixing sendOtp function in forgotPassword controller

### ISSUE THREAD

**Issue by aditya-garg-09-01-2002** [aditya-garg-09-01-2002/commencer#45]
**Describe the bug**

- Following up on the discussion in issue #33 and the successful PR #36.
- forgotPassword controller is still calling the function definition for sendOtp function.

**To Reproduce**

N/A

**Expected behavior**

- forgotPassword controller now also sendOtp function call.
- function call must be updated
- it shall also include the name argument.

**Screenshots**

None

**Your PC/browser/dev tool specifications (please complete the following information):**

N/A

**Additional context**

Ref file - src/controllers/user/forgotPassword.ts

**Comment by programmerraja** [comment]
can i work on this @aditya-garg-09-01-2002 
but i need to more clarity on what excatly i need to do can you plse expalin

**Comment by hasin-zaman** [comment]
@aditya-garg-09-01-2002 kindly assign me the issue

**Comment by aditya-garg-09-01-2002** [comment]
Looks like @hasin-zaman has already created a pr for the issue, I will be assigning this to him for now. 
@programmerraja if you wish, you can move to a different issue, I would love to create some issues for you.
If you both want, checkout Discussions tab for #49
