### ISSUE TITLE
[Documentation Requirement] Creating a discussion informing users how to create email API keys

### ISSUE THREAD

**Issue by aditya-garg-09-01-2002** [aditya-garg-09-01-2002/commencer#8]
**Describe the documentation updates required**
- Create a new discussion to explain the process of creating a new mail API key using google developer console.

**Reason for the update**
- To let users of npm package to effectively use API for sending OTP using mails.
- To specify acceptable process of creating API keys

**Expected outcome**
- A new discussion is created.
- This compactly and clearly tells users how to create their personalised API keys.

**Additional context**
- Use comments to discuss and understand how email API keys are generated ( if the process is unknown ) to effectively create documentation.

**Comment by chavdarohit** [comment]
hello i am a new contributor and i want to contribute into the hacktoberfest i know the steps to create the API if i create the discussion and upload it will it be count in the contribution ?

**Comment by aditya-garg-09-01-2002** [comment]
Creating a discussion won't count as a PR raised.
- For raising PR, you can create Contributing.md file in the root directory. ( .md file is very similar to .html only )
- Just list out the steps in a neat fashion.
- Raise a PR and you will be a step ahead for hacktoberfest.
- Just make sure you have registered on hacktoberfest's website as well.
- You can copy the same stuff for a new discussion and I will close the issue as well.

**Comment by aditya-garg-09-01-2002** [comment]
I have assigned the issue for you, you can ask for any further details if needed.

**Comment by chavdarohit** [comment]
okay thanks ill work on it and submit the PR as fast as possible today also i will upload in the discussion as well as in the .md file but i want to ask that should i put the filename as Contributing.md or for the name suggesting the discussion to create the email API keys

**Comment by aditya-garg-09-01-2002** [comment]
- file will be added as Contributing.md in the root folder itself.
- you can just put out a heading for now, informing others everyone about the process.
- rest for non-contributing developers, they can simply refer to discussions section.
- if you feel like, do include screenshots.

**Comment by aditya-garg-09-01-2002** [comment]
- you can create a discussion with a name whatever you find suitable in general category

**Comment by chavdarohit** [comment]
Done thanks 🙇

**Comment by aditya-garg-09-01-2002** [comment]
- I done seem to see a pull request been raised or a new discussion started.
- Upon checking your fork repo, it didn't show any updates as such as well.
- Possibly you have not committed or at least pushed the changes.
- You can create the file in your fork and make a pull request for Contributing.md file.
- And you can go ahead to create a new discussion as well in this repo.

**Comment by chavdarohit** [comment]
okay, yaa as per now i just fork but didn't updated yet

**Comment by aditya-garg-09-01-2002** [comment]
- so you can just ahead pushing your updates to your fork.
- then come to this repo, and do make a pull request towards main branch ( I will accept it rightaway).
- if you need help creating it, I can list out some screenshots as well.

**Comment by chavdarohit** [comment]
its fine ill make it

**Comment by aditya-garg-09-01-2002** [comment]
Yup, got the PR, I will be going through it once and we can move ahead after that.

**Comment by chavdarohit** [comment]
done :)

**Comment by chavdarohit** [comment]
after you verify and merge ill create the discussion

**Comment by aditya-garg-09-01-2002** [comment]
I saw the file, it misses on the part where we go to oauthplayground to get the Refresh token

**Comment by chavdarohit** [comment]
ohh okay sorry for the missing part ill add and get back to you for reviewing it

**Comment by chavdarohit** [comment]
i added the 5th point with the clarification and updated the PR kindly review it and if anything please ping me

**Comment by aditya-garg-09-01-2002** [comment]
There seemed to be some confusion regarding Refresh Token, I have added comments in the PR review itself, you can use that in 5th and 6th point and we are good to go.

**Comment by chavdarohit** [comment]
Okay

**Comment by chavdarohit** [comment]
sir you can add the labels and close the issue ;)

**Comment by aditya-garg-09-01-2002** [comment]
Sure, I will close the issue upon opening of the discussion.

**Comment by chavdarohit** [comment]
i have opened the discussion and also posted the content there 👍

**Comment by aditya-garg-09-01-2002** [comment]
Congratulations 👍

**Comment by aditya-garg-09-01-2002** [comment]
This marks close for this issue.
